Style/AsciiComments:
  Enabled: false
AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/**/*"
    - 'config/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'aws_lambda/**/*'
    - 'app/helpers/**/*'
Rails:
  Enabled: true
Metrics/AbcSize:
  Max: 20
LineLength:
  Max: 90
MethodLength:
  Max: 15
