mysql:
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_PASSWORD=docker
    - MYSQL_USER=docker
    - MYSQL_DATABASE=disneywt_development
  build: ./docker/mysql

redis:
  build: ./docker/redis

rails:
  build: .
  command: 'docker/rails/start_server.sh'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - mysql
    - redis
  environment:
    - DISNEYWT_DATABASE_USERNAME=root
    - DISNEYWT_DATABASE_PASSWORD=docker
    - DISNEYWT_DATABASE_HOST=mysql
    - DISNEYWT_REDIS_HOST=redis
    - DISNEYWT_REDIS_PORT=6379
    - DISNEYWT_REDIS_PASSWORD=docker
  volumes_from:
    - bundle

bundle:
  image: busybox
  volumes:
    - /bundle
