default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DISNEYWT_DATABASE_USERNAME'] %>
  password: <%= ENV['DISNEYWT_DATABASE_PASSWORD'] %>
  host: <%= ENV['DISNEYWT_DATABASE_HOST'] || 'localhost' %>
  port: 3306
  pool: 30
  timeout: 30000

development:
  <<: *default
  database: disneywt_development
  collation: utf8_general_ci
  charset: utf8

test:
  <<: *default
  database: disneywt_test
  collation: utf8_general_ci
  charset: utf8

production:
  <<: *default
  database: disneywt_production
  collation: utf8_general_ci
  charset: utf8
